### ISSUE TITLE
Some sentences in README file unclear/difficult to read.

### ISSUE THREAD

**Issue by KatelynKim** [Lombiq/Hastlayer-SDK#38]
There are a few unclear sentences in the README file due to lack of punctuation and awkward sentence structure.

For instance,

**"Since not C#, VisualBasic or other code but .NET Intermediate Language assemblies are transformed in theory any .NET language can be used, including C#, VB, F#, C++, Python, PHP, JavaScript..."**

Since not C#, VisualBasic or other code but .NET Intermediate Language assemblies are transformed --> Sentence is awkward as it begins with "not" instead of the subject, which is ".NET Intermediate Language assemblies". 

'...assemblies are transformed in theory any .NET language can be used," --> It is unclear to which clause the word "in theory" belongs to due to lack of punctuation. Depending on where the comma is placed, the sentence could mean two different things:
"Since...the assemblies are transformed in theory, any .NET languages can be used."
"Since... the assemblies are transformed, any .NET languages can be used in theory."

At any rate, it is better to remove "in theory" as it gives the impression that the developer is not sure about the range of languages the user can use on his program.

**Comment by Piedone** [comment]
Thanks for the feedback. I'd be happy to look at your suggestions under a PR.

"In theory" is actually exactly that: in theory, all .NET languages can be used due to Hastlayer processing compiled .NET assemblies, in practice until we test them we won't know.  For example, for F# support we needed to add some adjustments to Hatslayer.

**Comment by Piedone** [comment]
Thank you!
